### ISSUE TITLE
nice malware

### ISSUE THREAD

**Issue by xTrexy** [MidnightAnnie/AnnieDisc#2]
got 99999999999999 flags on VT

**Comment by ghost** [comment]
Damn, I was about to run it.

**Comment by MidnightAnnie** [comment]
It's not a virus. Your free to think it is, I have explained why it is flagged by some AV.

**Comment by MidnightAnnie** [comment]
Lol xtrexy I just noticed you GitHub account is new are you that dame idiot on Reddit :3
