### ISSUE TITLE
 am I doing this wrong?

### ISSUE THREAD

**Issue by A2uma0** [MidnightAnnie/AnnieDisc#3]
None of the functions seem to put out a vid, what should I press and in which directory will the vid be?

**Comment by MidnightAnnie** [comment]
Sry for late reply.

For it to work you drag and drop the Video/Gid or Audio file onto the exe

It will output it to the same dir as the file you dragged in.

If you have more Issues make sure you are using the latest Version (I tend to make mistakes a lot :3)

**Comment by MidnightAnnie** [comment]
But there are some issues with stuff so best to do Is drag the file to the same dir as the exe
