### ISSUE TITLE
annie_crash.mp4 simply dosent have a video

### ISSUE THREAD

**Issue by s-alad** [MidnightAnnie/AnnieDisc#6]
when i drag my "video,mp4" (length 00:00:06) onto the .exe and choose to create the crash at interval 00:00:04, everything works fine but the anime_crash.mp4 doesn't have a video on it and discord doesn't recognize it as an mp4. do you have any ideas why?

**Comment by MidnightAnnie** [comment]
Hmmm, there is one thing that comes to mind. 

Sometimes when the video is short it has a hard time stitching it back together for some reason.

Fixes: try extending the video first to something like 10-12 secs then doing it so in any video editing software just add a length to it. 

I might update the software with something like that built in to fix the issue before the newest update. 

But yeah try that fix for now I'll see too updating the app another time. 

Hope that works

**Comment by ghost** [comment]
I had the same issue as @ssaladd. I assume he dragged his video **inside of the cmd window** after launching the exe.

What I ended up doing was dragging the video **on top of the .exe**, picked my intervals and it produced the annie_crash.mp4 without error. I hope this helps.
